---
name: "mention"

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]
  pull_request:
    types: [opened, edited, review_requested]
  pull_request_review:
    types: [submitted]
  pull_request_review_comment:
    types: [created, edited]

  jobs:
    hello_world_job:
      runs-on: ubuntu-latest
      name: A job to say hello
      steps:
        - name: Hello world action step
          id: hello
          uses: sildeswj/github-to-slack@latest
          with:
            who-to-greet: "Mona the Octocat"
        # Use the output from the `hello` step
        - name: Get the output time
          run: echo "The time was ${{ steps.hello.outputs.time }}"
# jobs:
#   github_to_slack:
#     runs-on: ubuntu-latest
#     name: A job to say hello
#     steps:
#       - name: Test
#       - uses: sildeswj/github-to-slack@latest
#       - id: foo
#         with:
#           who-to-greet: "Mona the Octocat"
#       - run: echo random-number ${{ steps.foo.outputs.random-number }}
#         shell: bash

# jobs:
#   mention-to-slack:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Run
#         uses: abeyuya/actions-mention-to-slack@v2
#         with:
#           repo-token: ${{ secrets.GITHUB_TOKEN }}
#           slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
#           icon-url: https://img.icons8.com/color/256/000000/github-2.png
#           bot-name: 'Send Mention from abeyuya/actions-mention-to-slack'
#           run-id: ${{ github.run_id }}
