---
name: "mention"

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]
  pull_request:
    types: [opened, edited, review_requested]
  pull_request_review:
    types: [submitted]
  pull_request_review_comment:
    types: [created, edited]

jobs:
  github_to_slack:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: sildeswj
        uses: sildeswj/github-to-slack@latest
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          github-run-id: ${{ github.run_id }}
      # Use the output from the `hello` step
      - name: Get the output result
        run: echo "The result is ${{ steps.sildeswj.outputs.result }}"
# jobs:
#   mention-to-slack:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Run
#         uses: abeyuya/actions-mention-to-slack@v2
#         with:
#           repo-token: ${{ secrets.GITHUB_TOKEN }}
#           slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
#           icon-url: https://img.icons8.com/color/256/000000/github-2.png
#           bot-name: 'Send Mention from abeyuya/actions-mention-to-slack'
#           run-id: ${{ github.run_id }}
